inputs:
  files:
    required: true

outputs:
  ios:
    description: 'Whether any files changed that affects iOS build'
    value: ${{ steps.analyze.outputs.ios }}
  android:
    description: 'Whether any files changed that affects Android build'
    value: ${{ steps.analyze.outputs.android }}

runs:
  using: 'composite'
  steps:
    - name: '🧮 Decide which platforms to run e2e tests for'
      id: analyze
      shell: bash
      run: |
        run_ios="false"
        run_android="false"

        for file in ${{ inputs.files }}; do
          if [[ "$file" == "packages/"*"/ios/"* ]] || \
            [[ "$file" == "packages/"*".swift" ]] || \
            [[ "$file" == "packages/"*".podspec" ]] || \
            [[ "$file" == "packages/"*".xcodeproj"* ]] || \
            [[ "$file" == "packages/"*".xcworkspace"* ]] || \
            [[ "$file" == "packages/"*".plist" ]] || \
            [[ "$file" == "packages/"*".m" ]] || \
            [[ "$file" == "packages/"*".mm" ]]; then
            run_ios="true"
            continue
          fi

          if [[ "$file" == "packages/"*"/android/"* ]] || \
            [[ "$file" == "packages/"*".java" ]] || \
            [[ "$file" == "packages/"*".kt" ]] || \
            [[ "$file" == "packages/"*".gradle"* ]] || \
            [[ "$file" == "packages/"*".xml" ]] || \
            [[ "$file" == "packages/"*".pro" ]]; then
            run_android="true"
            continue
          fi

          run_ios="true"
          run_android="true"
          break
        done

        echo "Files in these platforms have changed: iOS=$run_ios, Android=$run_android"
        echo "ios=$run_ios" >> "$GITHUB_OUTPUT"
        echo "android=$run_android" >> "$GITHUB_OUTPUT"
